# Created with podman-5.3.2
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-03-05T18:48:43Z"
  labels:
    app: frangisk
  name: frangisk
spec:
  containers:
    - name: photography
      args:
        - -D
        - -f
        - /etc/lighttpd/lighttpd.conf
      image: localhost/lighttpd:latest
      volumeMounts:
        - mountPath: /var/
          name: photography
          readOnly: true
    - name: weblog
      args:
        - -D
        - -f
        - /etc/lighttpd/lighttpd.conf
      image: localhost/lighttpd:latest
      volumeMounts:
        - mountPath: /var
          name: weblog
          readOnly: true
  volumes:
    - name: photography
      hostPath:
        path: /home/liam/pods/frangisk/photography
        type: Directory
    - name: weblog
      hostPath: 
        path: /home/liam/pods/frangisk/weblog
        type: Directory   


