# Created with podman-5.3.2
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-03-05T18:48:43Z"
  labels:
    app: frangisk
  name: frangisk
spec:
  containers:
  - args:
    - -D
    - -f
    - /etc/lighttpd/lighttpd.conf
    image: localhost/lighttpd:latest
    name: photography
    ports:
    - containerPort: 82
      hostPort: 8080
    volumeMounts:
    - mountPath: /var/www/html
      name: photography
      readOnly: true
  - args:
    - -D
    - -f
    - /etc/lighttpd/lighttpd.conf
    image: localhost/lighttpd:latest
    name: weblog
    ports: 
    - containerPort: 81
      hostPort: 8081
    volumeMounts:
    - mountPath: /var/www/html
      name: weblog
      readOnly: true
  volumes:
  - hostPath:
      path: /home/liam/pods/frangisk/photography
      type: Directory
    name: photography
  - hostPath: 
      path: /home/liam/pods/frangisk/weblog
      type: Directory
    name: weblog
