# pluto network source of truth (table 3)

[rproxy-edge]
NAME_A=host
NAME_B=rproxy-edge
IP_A=192.168.50.0
IP_B=192.168.50.1
INTERFACE_A=host-pub
PORTS=80,443,25565

[lbmt-darkroom]
NAME_A=rproxy-edge
NAME_B=lbmt-darkroom
IP_A=172.16.1.0
IP_B=172.16.1.1
INTERFACE_A=pub-lbmt-darkroom

[mc-server]
NAME_A=rproxy-edge
NAME_B=mc-server
IP_A=172.16.5.0
IP_B=172.16.5.1
INTERFACE_A=pub-mc-server

[navid-server]
NAME_A=navid-server
NAME_B=navid-web
IP_A=10.254.1.0
IP_B=10.254.1.1
INTERFACE_A=to-navid-web
INTERFACE_B=to-navid-server

[navid-web]
NAME_A=rproxy-edge
NAME_B=navid-web
IP_A=172.16.7.0
IP_B=172.16.7.1
INTERFACE_A=pub-navid-web

[git-web]
NAME_A=rproxy-edge
NAME_B=git-web
IP_A=172.16.4.0
IP_B=172.16.4.1
INTERFACE_A=pub-git-web

[mc-ttyd-rcon]
NAME_A=rproxy-edge
NAME_B=mc-ttyd-rcon
IP_A=10.1.4.0
IP_B=10.1.4.1
INTERFACE_A=pri-mc-ttyd-rcon

[zfs-editor]
NAME_A=rproxy-edge
NAME_B=zfs-editor
IP_A=10.1.7.0
IP_B=10.1.7.1
INTERFACE_A=pri-zfs-editor

[zfs-preview]
NAME_A=zfs-editor
NAME_B=zfs-preview
IP_A=10.254.2.0
IP_B=10.254.2.1
INTERFACE_A=to-zfs-editor
INTERFACE_B=to-zfs-preview
