# pluto network source of truth (table 3)

[rproxy-edge]
NAME_A=host
NAME_B=rproxy-edge
IP_A=192.168.50.0
IP_B=192.168.50.1
INTERFACE_A=host-pub
PORTS=80,443

[lbmt-darkroom]
NAME_A=rproxy-edge
NAME_B=lbmt-darkroom
IP_A=172.16.1.0
IP_B=172.16.1.1
INTERFACE_A=pub-lbmt-darkroom

[navid-web]
NAME_A=navid-server
NAME_B=navid-web
IP_A=10.254.1.0
IP_B=10.254.1.1
INTERFACE_A=to-navid-web
INTERFACE_B=to-navid-server"
