# Created with podman-5.3.2
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-03-06T10:46:43Z"
  labels:
    app: michel
  name: michel
spec:
  containers:
  - args:
    - run
    - --config
    - /etc/caddy/Caddyfile
    image: localhost/caddy-reverse-proxy:latest
    name: reverse-proxy
    ports:
    - containerPort: 80
      hostPort: 80
#    - containerPort: 443
#      hostPort: 443
    networks: 
    - name: frangisk
    volumeMounts:
    - mountPath: /etc/caddy/
      name: caddy-config-volume
      readOnly: true
  volumes:
  - name: caddy-config-volume
    hostPath:
      path: /home/liam/pods/michel/reverse-proxy
      type: Directory
