# Created with podman-5.3.2
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-03-06T10:46:43Z"
  labels:
    app: michel
  name: michel
spec:
  containers:
  - name: http-reverse-proxy
    image: localhost/caddy-reverse-proxy:latest
    ports:
      - containerPort: 80
        hostPort: 80
      - containerPort: 443
        hostPort: 443
    args:
    - run
    - --config
    - /etc/caddy/Caddyfile
    volumeMounts:
    - mountPath: /etc/caddy/
      name: caddy-config-volume
      readOnly: true
  volumes:
  - name: caddy-config-volume
    hostPath:
      path: /home/liam/pods/michel/http-reverse-proxy
      type: Directory
