# Created with podman-5.3.2
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-03-06T10:46:43Z"
  labels:
    app: michel
  name: michel
spec:
  containers:
  - args:
    - run
    - --config
    - /etc/caddy/Caddyfile
    image: localhost/caddy-reverse-proxy:latest
    name: caddy-reverse-proxy
    ports:
    - containerPort: 80
      hostPort: 8080
    volumeMounts:
    - mountPath: /etc/caddy/
      name: caddyFile
      readOnly: true
  volumes:
  - hostPath:
      path: /home/liam/pods/michel/reverse-proxy
      type: Directory
    name: caddyFile

