# Created with podman-5.3.2
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-03-05T18:48:43Z"
  labels:
    app: eligius
  name: eligius
spec:
  containers:
    - name: git-ssh
      image: localhost/git-ssh:latest
      ports: 
        - containerPort: 22
          hostPort: 22
      volumeMounts:
        - mountPath: /srv/
          name: git
        - mountPath: /home/git/.ssh/authorized_keys
          name: authorized-keys
    - name: cgit
      image: localhost/cgit:latest
      ports: 
        - containerPort: 80
          hostPort: 0
      args:
        - -D
        - -f
        - /etc/lighttpd/lighttpd.conf
      volumeMounts:
        - name: cgit
          mountPath: /var
          subPath: var
          readOnly: true
        - name: cgit
          mountPath: /etc/cgitrc
          subPath: etc/cgitrc
          readOnly: true
#        - name: cgit
#          mountPath: /usr/share/webapps/
#          subPath: usr/share/webapps/cgit
#          readOnly: true
  volumes:
    - name: git
      hostPath: 
        path: /home/liam/pods/eligius/git
        type: Directory   
    - name: authorized-keys
      hostPath: 
        path: /home/liam/pods/eligius/ssh/authorized_keys
        type: File
    - name: cgit
      hostPath:
        path: /home/liam/pods/eligius/cgit/resources
        type: Directory
